version: '2.1'

services:
  mongo:
    image: mongo
    container_name: "mongodb"
    build: ./mongo
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ~/data/db:/data/db
    ports:
      - 27017:27017
  app:
    image: admin
    container_name: "admin"
    build: ./admin
    ports:
      - 9000:9000
